[package]
name = "linkforge"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Euraxluo (euraxluo@outlook.com)"]
version = "0.1.0"

# testnetv1 published-at 0x0
# testnetv2 published-at 0x0
# testnetv3 published-at 0x0
# mainnetv1 published-at 0x0
# mainnetv2 published-at 0x0
# mainnetv3 published-at 0x0
published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
# testnet "0x0"
# mainnet "0x0"
linkforge = "0x0"




